# Uncomment the next line to define a global platform for your project
source ‘https://github.com/iossocket/TWRepo.git’

platform :ios, '9.0'

target 'Container' do
  pod 'PodSample'
  pod 'RNSampleFeature', '0.0.1'
  pod 'RNGestureHandler', :path => '../rn/node_modules/react-native-gesture-handler'

  # Flutter
  flutter_application_path = '../flutter/'
  eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)
end
